version: '3.8'

services:
  postgres-db: # 👈 O el nombre que tenga tu servicio de base de datos
    image: postgres:15
    # ... tus configuraciones de puertos y environment ...
    healthcheck: # 👈 Mide si la BD ya acepta conexiones reales
      test: ["CMD-SHELL", "pg_isready -U postgres -d railway"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka_service # Apunta a la carpeta de tu Eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started

  auth-service:
    build: ./m1_auth_service
    depends_on:
      eureka-server:
        condition: service_started

  user-service:
    build: ./m2_user_service
    depends_on:
      eureka-server:
        condition: service_started
  
  prifile-service:
    build: ./m3_prifile_service
    depends_on:
      eureka-server:
        condition: service_started

  building-service:
    build: ./m4_building_service
    depends_on:
      eureka-server:
        condition: service_started

  room-service:
    build: ./m5_room-service
    depends_on:
      eureka-server:
        condition: service_started

  teacher-service:
    build: ./m6_teacher-service
    depends_on:
      eureka-server:
        condition: service_started

  curriculum-service:
    build: ./m7_curriculum_service
    depends_on:
      eureka-server:
        condition: service_started

  group-service:
    build: ./m8_group_service
    depends_on:
      eureka-server:
        condition: service_started

  schedule-service:
    build: ./m9_schedule_service
    depends_on:
      eureka-server:
        condition: service_started

  psychology-service:
    build: ./m11_psychology_service
    depends_on:
      eureka-server:
        condition: service_started

  mentorship-service:
    build: ./m12_mentorship_service
    depends_on:
      eureka-server:
        condition: service_started

  gene-service: # <-- Cambiado a minúsculas para que Docker no lo rechace
    build: ./Gene # <-- Este se queda igual porque tu carpeta real se llama 'Gene'
    ports:
      - "8000:8000"
    depends_on:
      eureka-server:
        condition: service_started