spring:
  application:
    name: m1-auth-service

  datasource:
    url: jdbc:postgresql://switchyard.proxy.rlwy.net:44805/railway
    username: postgres
    password: GcsEmbPNyJCDzIPDWiApeZlNfmtWKdTB
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: CRONOS2026_SECRET_KEY_256_BITS_LONG_ENOUGH_1234567890ABCDEF
  expiration: 3600000