spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://M1-AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            
            - id: user-service
              uri: lb://M2-USER-SERVICE
              predicates:
                - Path=/api/usuario/**
                
            - id: profesor-service
              uri: lb://M2-USER-SERVICE
              predicates:
                - Path=/api/profesores/**
                
            - id: estudiante-service
              uri: lb://M2-USER-SERVICE
              predicates:
                - Path=/api/estudiantes/**
                
            - id: profile-service
              uri: lb://m3-profile-service
              predicates:
                - Path=/api/v1/profiles/**

            - id: building-service
              uri: lb://m4-building-service
              predicates:
                - Path=/edificios/**

            - id: room-service
              uri: lb://m5-room-service
              predicates:
                - Path=/aulas/**

            - id: teacher-service
              uri: lb://m6-teacher-service
              predicates:
                - Path=/api/teachers/**

            - id: curriculum-service
              uri: lb://m7-curriculum-service
              predicates:
                - Path=/api/curriculum/**

            - id: group-service
              uri: lb://m8-group-service
              predicates:
                - Path=/api/v1/grupos/**

            - id: schedule-service
              uri: lb://m9-schedule-service
              predicates:
                - Path=/api/schedule/**

            - id: psychology-service
              uri: lb://m11-psychology-service
              predicates:
                - Path=/api/psychology/**

            - id: mentorship-service
              uri: lb://m12-mentorship-service
              predicates:
                - Path=/api/mentorship/**

            - id: gene-service
              uri: http://gene-service:8000
              predicates:
                - Path=/api/gene/**

            - id: turno-service
              uri: lb://m10-turno-service
              predicates:
                - Path=/api/turnos/**

            - id: profesor-asignatura-service
              uri: lb://m14-profesor-asignatura-service
              predicates:
                - Path=/api/profesor-asignatura/**

            - id: profesor-aula-service
              uri: lb://m14-profesor-asignatura-service
              predicates:
                - Path=/api/profesor-aula/**

            - id: periodo-service
              uri: lb://m15-periodo-service
              predicates:
                - Path=/api/periodos/**

            - id: division-service
              uri: lb://m13-division-service
              predicates:
                - Path=/divisiones/**
          
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    groups-order: asc