spring.application.name=m5-room-service
server.port=8085

# Configuración de la conexión a la Base de Datos
spring.datasource.url=jdbc:postgresql://switchyard.proxy.rlwy.net:44805/railway
spring.datasource.username=postgres
spring.datasource.password=GcsEmbPNyJCDzIPDWiApeZlNfmtWKdTB
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN EUREKA UNIFICADA ---
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}